driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
- name: ubuntu-14.04
  driver_config:
    network:
      - ["forwarded_port", {guest: 8080, host: 8080}]
      - ["forwarded_port", {guest: 8081, host: 8081}]
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: centos-5.11
- name: centos-6.7
- name: centos-7.2
- name: opensuse-13.2
  driver:
    box: opensuse-13.2
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_opensuse-13.2-x86_64_chef-provisionerless.box
  run_list:
    - recipe[zypper]

suites:
- name: multi-instance
  run_list: ["recipe[test::default]"]
